name: demultiplex
description: Demultiplexing of raw sequencing data
argument_groups:
  - name: Input arguments
    arguments:
      - name: --input
        description: Directory containing raw sequencing data
        type: file
        required: true
      - name: --sample_sheet
        description: Sample sheet
        type: file
        required: true
  - name: Output arguments
    arguments:
      - name: --output
        description: Directory to write fastq data to
        type: file
        direction: output
        required: false
        default: "$id/fastq"
      - name: "--output_falco"
        description: Directory to write falco output to
        type: file
        direction: output
        required: false
        default: "$id/falco"
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf

test_resources:
  - type: nextflow_script
    path: test.nf
    entrypoint: test_wf

dependencies:
  - name: io/untar
    repository: local
  - name: bcl_convert
    repository: bb
  - name: falco
    repository: bb
repositories:
  - name: bb
    type: vsh
    repo: viash-hub/biobase

runners:
  - type: nextflow

engines:
  - type: native
