name: demultiplex
description: Demultiplexing of raw sequencing data
argument_groups:
  - name: Input arguments
    arguments:
      - name: --id
        description: Unique identifier for the run
        type: string
      - name: --input
        description: Directory containing raw sequencing data
        type: file
        required: true
      - name: --run_information
        description: |
          CSV file containing sample information, which will be used as 
          input for the demultiplexer. Canonically called 'SampleSheet.csv' (Illumina)
          or 'RunManifest.csv' (Element Biosciences). If not specified,
          will try to autodetect the sample sheet in the input directory.
          Requires --demultiplexer to be set.
        type: file
        required: false
      - name: "--demultiplexer"
        type: string
        required: false
        choices: ["bases2fastq", "bclconvert"]
        description: |
          Demultiplexer to use, choice depends on the provider
          of the instrument that was used to generate the data.
          When not using --sample_sheet, specifying this argument is not
          required.
  - name: Output arguments
    arguments:
      - name: --output
        description: Directory to write fastq data to
        type: file
        direction: output
        required: false
        default: "$id/fastq"
      - name: "--output_sample_qc"
        description: Directory to write FastQC output to
        type: file
        direction: output
        required: false
        multiple: true
        default: "$id/qc/fastqc"
      - name: "--multiqc_output"
        description: Location where to write MultiQC output to
        type: file
        direction: output
        required: false
        default: "$id/qc/multiqc_report.html"
      - name: "--output_run_information"
        type: file
        direction: "output"
        required: true
        default: "$id/run_information.csv"
      - name: "--demultiplexer_logs"
        type: file
        direction: output
        required: true
        default: "$id/demultiplexer_logs"
  - name: "Other arguments"
    arguments:
      - name: --skip_copycomplete_check
        type: boolean_true
        description: |
          Disable the check for the presence of a "CopyComplete.txt" file in input
          directory in case of Illumina data.
        
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf

test_resources:
  - type: nextflow_script
    path: test.nf
    entrypoint: test_illumina
  - type: nextflow_script
    path: test.nf
    entrypoint: test_bases2fastq
  - type: nextflow_script
    path: test.nf
    entrypoint: test_no_index

dependencies:
  - name: io/untar
    repository: local
  - name: dataflow/gather_fastqs_and_validate
    repository: local
  - name: io/interop_summary_to_csv
    repository: local
  - name: dataflow/combine_samples
    repository: local
  - name: bcl_convert
    repository: bb
  - name: bases2fastq
    repository: bb
  - name: fastqc
    repository: bb
  - name: multiqc
    repository: bb
repositories:
  - name: bb
    type: vsh
    repo: biobox
    tag: v0.3.1

runners:
  - type: nextflow

engines:
  - type: native
