name: runner
description: Runner for demultiplexing of raw sequencing data
argument_groups:
  - name: Input arguments
    arguments:
      - name: --input
        description: |
          Base directory of the canonical form `s3://<bucket>/<path>/<RunID>/`.
          A tarball (tar.gz, .tgz, .tar) containing run information can be provided in which
          case the RunID is set to the name of the tarball without the extension.
        type: file
        required: true
      - name: --run_information
        description: |
          CSV file containing sample information, which will be used as 
          input for the demultiplexer. Canonically called 'SampleSheet.csv' (Illumina)
          or 'RunManifest.csv' (Element Biosciences). If not specified,
          will try to autodetect the sample sheet in the input directory.
          Requires --demultiplexer to be set.
        type: file
        required: false
      - name: "--demultiplexer"
        type: string
        required: false
        choices: ["bases2fastq", "bclconvert"]
        description: |
          Demultiplexer to use, choice depends on the provider
          of the instrument that was used to generate the data.
          When not using --sample_sheet, specifying this argument is not
          required.
  - name: Annotation flags
    arguments:
      - name: --plain_output
        description: |
          Flag to indicate that the output should be stored directly under $publish_dir rather than
          under a subdirectory structure runID/<date_time>_demultiplex_<version>/.
        type: boolean_true
  - name: Output arguments
    arguments:
      - name: --fastq_output
        type: file
        direction: output
        default: "fastq"
      - name: --sample_qc_output
        type: file
        direction: output
        default: "qc/fastqc"
      - name: --multiqc_output
        type: file
        direction: output
        default: "qc/multiqc_report.html"
      - name: "--demultiplexer_logs"
        type: file
        direction: output
        default: "demultiplexer_logs"
  - name: "Other arguments"
    arguments:
      - name: --skip_copycomplete_check
        type: boolean_true
        description: |
          Disable the check for the presence of a "CopyComplete.txt" file in input
          directory in case of Illumina data.
resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
test_resources:
  - type: nextflow_script
    path: test.nf
    entrypoint: test

dependencies:
  - name: demultiplex
    repository: local
  - name: io/publish
    repository: local

runners:
  - type: nextflow

engines:
  - type: native
